version: "3.3"

services:
  web:
    image: nginx:1.19.7-alpine
    environment:
      - VIRTUAL_HOST=howtosay.editorium.net
      - LETSENCRYPT_HOST=howtosay.editorium.net
    volumes:
      - ./code/src:/code/src
      - ./nginx.conf.server:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    volumes:
      - ./code/src:/code/src

networks:
  default:
    external:
      name: nginx-proxy